[{:name "algo.monads"
  :owners []}
 {:name "core.incubator"
  :owners []}
 {:name "core.logic"
  :owners ["davidnolen"]}
 {:name "core.unify"
  :owners []}
 {:name "data.csv"
  :owners []}
 {:name "data.finger-tree"
  :owners ["Chouser"]}
 {:name "data.json"
  :owners ["stuartsierra"]}
 {:name "data.xml"
  :owners []}
 {:name "data.zip"
  :owners []}
 {:name "io.incubator"
  :owners []}
 {:name "java.classpath"
  :owners []}
 {:name "java.data"
  :owners ["cosminstejerean"]}
 {:name "java.jdbc"
  :owners ["seancorfield"]}
 {:name "java.jmx"
  :owners []}
 {:name "test.generative"
  :owners []}
 {:name "tools.cli"
  :owners ["garethjones"]}
 {:name "tools.logging"
  :owners []}
 {:name "tools.macro"
  :owners []}
 {:name "tools.namespace"
  :owners []}
 {:name "tools.nrepl"
  :owners []}]
